// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dishFieldNames          = builder.RawFieldNames(&Dish{})
	dishRows                = strings.Join(dishFieldNames, ",")
	dishRowsExpectAutoSet   = strings.Join(stringx.Remove(dishFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dishRowsWithPlaceHolder = strings.Join(stringx.Remove(dishFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDishIdPrefix   = "cache:dish:id:"
	cacheDishNamePrefix = "cache:dish:name:"
)

type (
	dishModel interface {
		Insert(ctx context.Context, data *Dish) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Dish, error)
		FindOneByName(ctx context.Context, name string) (*Dish, error)
		Update(ctx context.Context, data *Dish) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDishModel struct {
		sqlc.CachedConn
		table string
	}

	Dish struct {
		Id          int64           `db:"id"`          // 主键
		Name        string          `db:"name"`        // 菜品名称
		CategoryId  int64           `db:"category_id"` // 菜品分类id
		Price       sql.NullFloat64 `db:"price"`       // 菜品价格
		Image       sql.NullString  `db:"image"`       // 图片
		Description sql.NullString  `db:"description"` // 描述信息
		Status      int64           `db:"status"`      // 0 停售 1 起售
		CreateTime  sql.NullTime    `db:"create_time"` // 创建时间
		UpdateTime  sql.NullTime    `db:"update_time"` // 更新时间
		CreateUser  sql.NullInt64   `db:"create_user"` // 创建人
		UpdateUser  sql.NullInt64   `db:"update_user"` // 修改人
	}
)

func newDishModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDishModel {
	return &defaultDishModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`dish`",
	}
}

func (m *defaultDishModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	dishIdKey := fmt.Sprintf("%s%v", cacheDishIdPrefix, id)
	dishNameKey := fmt.Sprintf("%s%v", cacheDishNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, dishIdKey, dishNameKey)
	return err
}

func (m *defaultDishModel) FindOne(ctx context.Context, id int64) (*Dish, error) {
	dishIdKey := fmt.Sprintf("%s%v", cacheDishIdPrefix, id)
	var resp Dish
	err := m.QueryRowCtx(ctx, &resp, dishIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dishRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDishModel) FindOneByName(ctx context.Context, name string) (*Dish, error) {
	dishNameKey := fmt.Sprintf("%s%v", cacheDishNamePrefix, name)
	var resp Dish
	err := m.QueryRowIndexCtx(ctx, &resp, dishNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", dishRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDishModel) Insert(ctx context.Context, data *Dish) (sql.Result, error) {
	dishIdKey := fmt.Sprintf("%s%v", cacheDishIdPrefix, data.Id)
	dishNameKey := fmt.Sprintf("%s%v", cacheDishNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, dishRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.CategoryId, data.Price, data.Image, data.Description, data.Status, data.CreateUser, data.UpdateUser)
	}, dishIdKey, dishNameKey)
	return ret, err
}

func (m *defaultDishModel) Update(ctx context.Context, newData *Dish) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	dishIdKey := fmt.Sprintf("%s%v", cacheDishIdPrefix, data.Id)
	dishNameKey := fmt.Sprintf("%s%v", cacheDishNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dishRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.CategoryId, newData.Price, newData.Image, newData.Description, newData.Status, newData.CreateUser, newData.UpdateUser, newData.Id)
	}, dishIdKey, dishNameKey)
	return err
}

func (m *defaultDishModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDishIdPrefix, primary)
}

func (m *defaultDishModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dishRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDishModel) tableName() string {
	return m.table
}
