// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dishFlavorFieldNames          = builder.RawFieldNames(&DishFlavor{})
	dishFlavorRows                = strings.Join(dishFlavorFieldNames, ",")
	dishFlavorRowsExpectAutoSet   = strings.Join(stringx.Remove(dishFlavorFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dishFlavorRowsWithPlaceHolder = strings.Join(stringx.Remove(dishFlavorFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDishFlavorIdPrefix = "cache:dishFlavor:id:"
)

type (
	dishFlavorModel interface {
		Insert(ctx context.Context, data *DishFlavor) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DishFlavor, error)
		Update(ctx context.Context, data *DishFlavor) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDishFlavorModel struct {
		sqlc.CachedConn
		table string
	}

	DishFlavor struct {
		Id     int64          `db:"id"`      // 主键
		DishId int64          `db:"dish_id"` // 菜品
		Name   sql.NullString `db:"name"`    // 口味名称
		Value  sql.NullString `db:"value"`   // 口味数据list
	}
)

func newDishFlavorModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDishFlavorModel {
	return &defaultDishFlavorModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`dish_flavor`",
	}
}

func (m *defaultDishFlavorModel) Delete(ctx context.Context, id int64) error {
	dishFlavorIdKey := fmt.Sprintf("%s%v", cacheDishFlavorIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, dishFlavorIdKey)
	return err
}

func (m *defaultDishFlavorModel) FindOne(ctx context.Context, id int64) (*DishFlavor, error) {
	dishFlavorIdKey := fmt.Sprintf("%s%v", cacheDishFlavorIdPrefix, id)
	var resp DishFlavor
	err := m.QueryRowCtx(ctx, &resp, dishFlavorIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dishFlavorRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDishFlavorModel) Insert(ctx context.Context, data *DishFlavor) (sql.Result, error) {
	dishFlavorIdKey := fmt.Sprintf("%s%v", cacheDishFlavorIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, dishFlavorRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DishId, data.Name, data.Value)
	}, dishFlavorIdKey)
	return ret, err
}

func (m *defaultDishFlavorModel) Update(ctx context.Context, data *DishFlavor) error {
	dishFlavorIdKey := fmt.Sprintf("%s%v", cacheDishFlavorIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dishFlavorRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DishId, data.Name, data.Value, data.Id)
	}, dishFlavorIdKey)
	return err
}

func (m *defaultDishFlavorModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheDishFlavorIdPrefix, primary)
}

func (m *defaultDishFlavorModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dishFlavorRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDishFlavorModel) tableName() string {
	return m.table
}
