// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	setmealFieldNames          = builder.RawFieldNames(&Setmeal{})
	setmealRows                = strings.Join(setmealFieldNames, ",")
	setmealRowsExpectAutoSet   = strings.Join(stringx.Remove(setmealFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	setmealRowsWithPlaceHolder = strings.Join(stringx.Remove(setmealFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSetmealIdPrefix   = "cache:setmeal:id:"
	cacheSetmealNamePrefix = "cache:setmeal:name:"
)

type (
	setmealModel interface {
		Insert(ctx context.Context, data *Setmeal) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Setmeal, error)
		FindOneByName(ctx context.Context, name string) (*Setmeal, error)
		Update(ctx context.Context, data *Setmeal) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSetmealModel struct {
		sqlc.CachedConn
		table string
	}

	Setmeal struct {
		Id          int64          `db:"id"`          // 主键
		CategoryId  int64          `db:"category_id"` // 菜品分类id
		Name        string         `db:"name"`        // 套餐名称
		Price       float64        `db:"price"`       // 套餐价格
		Status      int64          `db:"status"`      // 售卖状态 0:停售 1:起售
		Description sql.NullString `db:"description"` // 描述信息
		Image       sql.NullString `db:"image"`       // 图片
		CreateTime  sql.NullTime   `db:"create_time"` // 创建时间
		UpdateTime  sql.NullTime   `db:"update_time"` // 更新时间
		CreateUser  sql.NullInt64  `db:"create_user"` // 创建人
		UpdateUser  sql.NullInt64  `db:"update_user"` // 修改人
	}
)

func newSetmealModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSetmealModel {
	return &defaultSetmealModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`setmeal`",
	}
}

func (m *defaultSetmealModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	setmealIdKey := fmt.Sprintf("%s%v", cacheSetmealIdPrefix, id)
	setmealNameKey := fmt.Sprintf("%s%v", cacheSetmealNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, setmealIdKey, setmealNameKey)
	return err
}

func (m *defaultSetmealModel) FindOne(ctx context.Context, id int64) (*Setmeal, error) {
	setmealIdKey := fmt.Sprintf("%s%v", cacheSetmealIdPrefix, id)
	var resp Setmeal
	err := m.QueryRowCtx(ctx, &resp, setmealIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", setmealRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSetmealModel) FindOneByName(ctx context.Context, name string) (*Setmeal, error) {
	setmealNameKey := fmt.Sprintf("%s%v", cacheSetmealNamePrefix, name)
	var resp Setmeal
	err := m.QueryRowIndexCtx(ctx, &resp, setmealNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", setmealRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSetmealModel) Insert(ctx context.Context, data *Setmeal) (sql.Result, error) {
	setmealIdKey := fmt.Sprintf("%s%v", cacheSetmealIdPrefix, data.Id)
	setmealNameKey := fmt.Sprintf("%s%v", cacheSetmealNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, setmealRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CategoryId, data.Name, data.Price, data.Status, data.Description, data.Image, data.CreateUser, data.UpdateUser)
	}, setmealIdKey, setmealNameKey)
	return ret, err
}

func (m *defaultSetmealModel) Update(ctx context.Context, newData *Setmeal) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	setmealIdKey := fmt.Sprintf("%s%v", cacheSetmealIdPrefix, data.Id)
	setmealNameKey := fmt.Sprintf("%s%v", cacheSetmealNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, setmealRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CategoryId, newData.Name, newData.Price, newData.Status, newData.Description, newData.Image, newData.CreateUser, newData.UpdateUser, newData.Id)
	}, setmealIdKey, setmealNameKey)
	return err
}

func (m *defaultSetmealModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSetmealIdPrefix, primary)
}

func (m *defaultSetmealModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", setmealRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSetmealModel) tableName() string {
	return m.table
}
